apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://prom:9090
  basicAuth:
  basicAuthUser: admin
  isDefault: true
  jsonData:
     tlsAuth: false
     tlsAuthWithCACert: false
  version: 1
  editable: false
